# Generated by Django 5.2.5 on 2025-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='violence_snippets/'),
        ),
    ]
